services:
  postgres:
    image: postgres:16
    container_name: postgres-finance
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: financas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: api-finance:1.1.4
    container_name: api-finance
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data:
