spring.application.name=api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

aws.s3.bucketName=${AWS_BUCKET_NAME}
aws.region=${AWS_REGION}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
app.cookie.secure=${COOKIE_SECURE}