spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/financas_db
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

aws.s3.bucketName=finance-bucket-profile-images
aws.region=us-east-1

jwt.secret=2521fde28ce3e413e0ef377dd1be35ba
jwt.expiration=86400000